### ISSUE TITLE
письма и эффекты. type: 1

### ISSUE THREAD

**Issue by birdiecode** [birdiecode/postman#12]

**Comment by dddd1111111111** [comment]
я нарисовал различные письма. и эффекты к ним (грязь, потертость)

**Comment by dddd1111111111** [comment]
https://disk.yandex.ru/d/H3-UKdUY8IMpwg
ef- effects для каждого типа письма свой эффект.  
**Появляется** рандомно, **в количестве не более 2-х слоев с эффектом.**

**Comment by dddd1111111111** [comment]
![Image](https://user-images.githubusercontent.com/48757649/192150965-38a4edee-1481-4461-a098-bc2a7c8f52ca.png)
