### ISSUE TITLE
сконвертировать цифры в шрифт формата fnt

### ISSUE THREAD

**Issue by birdiecode** [birdiecode/postman#18]

**Comment by birdiecode** [comment]
https://disk.yandex.ru/d/6esjcg3qbhAH9w
https://drive.google.com/drive/folders/1DRevo5aCozfE6Knr9CabVK3NhJ-duzT-?usp=sharing

**Comment by mitrofasik** [comment]
http://ru.fontzzz.com/font/11208_brushed.htm
заебался. вот используй эти.

**Comment by mitrofasik** [comment]
http://ru.fontzzz.com/font/11211_edo.htm
выбирай какой хочешь
